// @flow

export const UPDATE_MARINES: "UPDATE_MARINES" = "UPDATE_MARINES";
export const UPDATE_CIVILIANS: "UPDATE_CIVILIANS" = "UPDATE_CIVILIANS";

export const GET_NEW_STORY: "GET_NEW_STORY" = "GET_NEW_STORY";
export const UPDATE_STORY_NODE: "UPDATE_STORY_NODE" = "UPDATE_STORY_NODE";
export const FINISH_STORY: "FINISH_STORY" = "FINISH_STORY";